const games = [
  {
    id: "forehead-tag",
    name: "Forehead Tag",
    phase: 1,
    position: "Kneeling",
    duration: 8,
    skill: "Head safety, spatial awareness",
    setup: "Both partners start kneeling, forehead to forehead, one hand on each other's shoulder.",
    goal: "Touch your partner's knee without letting them touch yours.",
    constraints: "Must maintain forehead contact at all times. No grabbing.",
    cues: "Make them move their head. If they are thinking about your head, they are not thinking about their knee.",
    realWorld: "Keeping your head safe and your eyes on the threat is priority one in any confrontation.",
    easier: "Increase the target area (touch the hip instead of the knee).",
    harder: "Standing instead of kneeling.",
  },
  {
    id: "wrist-connection",
    name: "Wrist Connection Game",
    phase: 1,
    position: "Standing",
    duration: 8,
    skill: "Grip fighting, maintaining connection",
    setup: "Standing. Both partners grip one opposite wrist.",
    goal: "Get a two-on-one grip OR press your forehead against the side of their head/neck.",
    constraints: "No strikes. Must maintain at least one point of contact at all times.",
    cues: "Control their hand and you control their body. Feel where their pressure goes.",
    realWorld: "Most street altercations start with someone grabbing you. Managing that connection is survival.",
    easier: "Allow any contact point.",
    harder: "Add a third goal: take them down.",
  },
  {
    id: "base-and-balance",
    name: "Base and Balance",
    phase: 1,
    position: "Kneeling",
    duration: 8,
    skill: "Stability under pressure",
    setup: "Both partners on knees in front of each other. Hands on each other's shoulders.",
    goal: "Make your partner post (put a hand on the ground).",
    constraints: "No grabbing below the waist. No striking. Both partners must move.",
    cues: "Feel where their weight is. Push there. When they push back, move around it.",
    realWorld: "If someone pushes you, your ability to stay on your feet determines everything.",
    easier: "Single point of contact.",
    harder: "Standing base.",
  },
  {
    id: "structure-connections",
    name: "Structure and Connections",
    phase: 1,
    position: "Seated Guard",
    duration: 10,
    skill: "Frames, distance management",
    setup: "Bottom seated. Top kneeling, hands on bottom's chest.",
    goal: "Bottom: create frames that keep top's weight off. Top: collapse frames to establish chest contact.",
    constraints: "Top cannot grab or pull. Only forward pressure. Bottom cannot grab either.",
    cues: "Your arms are not noodles. Make a shelf. Their weight should go into the floor, not your chest.",
    realWorld: "Knowing how to frame and create space on the ground is the highest-ROI skill for beginners.",
    easier: "Bottom can use both hands on the floor.",
    harder: "Top can grab the legs.",
  },
  {
    id: "hip-pinch-standup",
    name: "Hip Pinch / Stand Up",
    phase: 2,
    position: "Supine Guard",
    duration: 10,
    skill: "Standing up under pressure",
    setup: "Bottom on back. Top in open guard controlling bottom's knees.",
    goal: "Bottom: stand up. Top: prevent them from standing.",
    constraints: "Top can only use hands on bottom's knees/shin. No chest pressure. Bottom cannot grab top.",
    cues: "Your hips are a hinge. When your foot hits the floor, stand.",
    realWorld: "If you end up on your back in a real situation, the goal is to stand up as fast as possible.",
    easier: "Bottom can grab a wrist for help.",
    harder: "Add striking threat (top lifts a hand as a visual cue).",
  },
  {
    id: "shin-surfing",
    name: "Shin Surfing",
    phase: 2,
    position: "Seated Guard",
    duration: 8,
    skill: "Distance control",
    setup: "Bottom seated. Top standing in front.",
    goal: "Bottom: control distance with feet on top's hips/shin. Top: break through to establish contact.",
    constraints: "Top cannot grab the feet. Bottom's feet stay on top's body.",
    cues: "Your feet are your first line of defense. If you feel their hips, you feel what they plan.",
    realWorld: "Distance management is the most underrated self-defense skill.",
    easier: "Bottom can use hands on the floor.",
    harder: "Bottom must stand up as secondary goal.",
  },
  {
    id: "causing-posts",
    name: "Causing Posts",
    phase: 2,
    position: "Seated Guard",
    duration: 8,
    skill: "Off-balancing",
    setup: "Bottom seated. Top kneeling. Bottom has two points of connection on hips or sleeves.",
    goal: "Bottom: make the top post (hand on mat). Top: maintain upright posture.",
    constraints: "Bottom cannot sweep. The post is the goal. Top must engage forward.",
    cues: "Pull them into a space they do not want to be. The post is their body admitting defeat.",
    realWorld: "Off-balancing is the foundation of every takedown, sweep, and escape.",
    easier: "Both posts count.",
    harder: "Bottom must make both hands post simultaneously.",
  },
  {
    id: "ball-of-yarn",
    name: "Ball of Yarn",
    phase: 2,
    position: "Half Guard",
    duration: 10,
    skill: "Shield retention",
    setup: "Bottom in half guard with knee shield. Top passing on their side.",
    goal: "Bottom: maintain shield and prevent chest contact. Top: collapse shield.",
    constraints: "Bottom cannot go to closed guard. Top cannot jump over the shield.",
    cues: "Your knee is the door. If they collapse it, open it again. One frame at a time.",
    realWorld: "Half guard is common in any grappling situation. Shield retention keeps you one step from recovery.",
    easier: "Bottom can use both hands on the floor.",
    harder: "Bottom must sweep as primary goal.",
  },
  {
    id: "front-headlock-back",
    name: "Front Headlock to Back",
    phase: 3,
    position: "Turtle",
    duration: 8,
    skill: "Front headlock offense",
    setup: "Top has front headlock. Bottom on hands and knees.",
    goal: "Top: take the back. Bottom: clear the head and face top.",
    constraints: "Top cannot choke. Must work to the back. Bottom must actively improve.",
    cues: "If you have the head, you have the dog. Circle to the back.",
    realWorld: "The front headlock is a high-percentage, real-world position.",
    easier: "Top can use the near wrist as a handle.",
    harder: "Bottom can stand up.",
  },
  {
    id: "open-guard-sweeping",
    name: "Open Guard Sweeping",
    phase: 3,
    position: "Open Guard",
    duration: 10,
    skill: "Reversing position",
    setup: "Open guard (supine). Top standing controlling bottom's ankles.",
    goal: "Bottom: sweep the top. Top: pass the guard.",
    constraints: "Bottom cannot attack submissions. Top must work through the legs.",
    cues: "Their forward pressure is the engine. When they push in, pull. When they pull back, follow.",
    realWorld: "Sweeping someone off balance and reversing position is a core practical skill.",
    easier: "Sweeping from half guard instead.",
    harder: "Add striking threat for top.",
  },
  {
    id: "hip-and-shoulder",
    name: "Hip and Shoulder Connection",
    phase: 3,
    position: "Back Control",
    duration: 10,
    skill: "Back control / escape",
    setup: "Top has back control with one hook. Bottom on hands and knees.",
    goal: "Top: secure second hook + connect hands on hips/shoulders. Bottom: turn and face.",
    constraints: "Top cannot submit. Must establish position first.",
    cues: "Hips and shoulders. If you have both, you have them.",
    realWorld: "Back control is the safest dominant position. Learning to take and escape it is core.",
    easier: "Top starts with both hooks.",
    harder: "Bottom starts with one hand free.",
  },
  {
    id: "ankle-wars",
    name: "Ankle Wars",
    phase: 3,
    position: "Scramble",
    duration: 8,
    skill: "Chaos management",
    setup: "Both sit facing, legs extended, hands beside hips.",
    goal: "Be first to grab both of your partners ankles.",
    constraints: "Cannot push off partners body. Hands start off the mat.",
    cues: "The scramble is the most dangerous moment. Stay calm. Find the feet.",
    realWorld: "Scrambles happen constantly. The person who stays calm under chaos wins.",
    easier: "Only need to grab one ankle.",
    harder: "Grab both ankles and pull them to your side.",
  },
  {
    id: "submission-hunting-back",
    name: "Submission Hunting (Back)",
    phase: 4,
    position: "Back Control",
    duration: 10,
    skill: "Finishing from back",
    setup: "Top has both hooks in with body triangle.",
    goal: "Top: submit with upper body attack. Bottom: escape back control.",
    constraints: "Top cannot use second hook until attacking. Bottom must escape body triangle first.",
    cues: "Do not rush. The back is the safest place. Take your time.",
    realWorld: "Back control is the apex of positional dominance. Patience and precision win here.",
    easier: "Top starts with hand on the chin.",
    harder: "Bottom can stand up.",
  },
  {
    id: "creative-starts",
    name: "Creative Starts",
    phase: 4,
    position: "Variable",
    duration: 8,
    skill: "Unpredictability",
    setup: "Unusual start position (belly down, back-to-back, holding a foot, etc).",
    goal: "First to establish dominant position (mount, back, or side control).",
    constraints: "Both start simultaneously. Round ends on clear dominance.",
    cues: "Do not think. React. The unusual position is the equalizer.",
    realWorld: "Real situations never start on a mat. Training from weird starts builds adaptability.",
    easier: "Give one partner a head start.",
    harder: "Swap who starts in the worse position.",
  },
  {
    id: "no-knees",
    name: "No Knees",
    phase: 4,
    position: "Scramble",
    duration: 8,
    skill: "Surface adaptability",
    setup: "Both partners on knees facing each other.",
    goal: "First to establish dominant position.",
    constraints: "Neither player may touch their knees to the mat.",
    cues: "Your knees are a crutch. If you can move without them, you can move anywhere.",
    realWorld: "Surfaces vary. Gravel, concrete, grass. Training without knees makes you functional anywhere.",
    easier: "One knee allowed.",
    harder: "No hands either (torso and legs only).",
  },
  {
    id: "triangle",
    name: "Triangle Arm In / Arm Out",
    phase: 4,
    position: "Closed Guard",
    duration: 10,
    skill: "High-percentage finish",
    setup: "Bottom in closed guard. Top posture broken.",
    goal: "Bottom: set up and finish triangle. Top: posture up and pass.",
    constraints: "Bottom must attack triangle. Top cannot disengage and stand up.",
    cues: "The triangle starts in your hips, not your legs. Trap the arm, the rest is leverage.",
    realWorld: "The triangle is one of the highest-percentage submissions for a smaller person.",
    easier: "Top cannot use free hand to defend.",
    harder: "Bottom must chain triangle into arm bar if lost.",
  },
  {
    id: "belly-forehead-tag",
    name: "Belly Forehead Tag",
    phase: 0,
    position: "Kneeling",
    duration: 8,
    skill: "Striking head position",
    setup: "Both on knees, forehead to belly, hands on mat.",
    goal: "Touch partners lower back. Keep them from touching yours.",
    constraints: "Must maintain belly-to-head or chest-to-head contact.",
    cues: "If your head goes to their belly, they cannot see your hands.",
    realWorld: "Head position in striking is everything.",
    easier: "Single hand touch only.",
    harder: "Standing.",
  },
  {
    id: "poopy-hands",
    name: "Poopy Hands",
    phase: 0,
    position: "Standing",
    duration: 8,
    skill: "Takedown setup",
    setup: "Standing. Both in loose collar-tie.",
    goal: "Get both hands on the same arm (two-on-one) then immediately execute a takedown.",
    constraints: "No shooting without the two-on-one. Reset if grip breaks.",
    cues: "When you control the hand, you control the hip. When you control the hip, you control the takedown.",
    realWorld: "The two-on-one creates asymmetry that works for striking, clinch entries, and self-defense.",
    easier: "One grip from the wrist is enough.",
    harder: "Partner can use free hand to strike (simulated).",
  },
  {
    id: "cover-head-shoulders",
    name: "Cover the Head and Shoulders",
    phase: 0,
    position: "Turtle",
    duration: 8,
    skill: "Positional defense",
    setup: "Top has front headlock. Bottom is turtled with head covered.",
    goal: "Top: break turtle and establish chest-to-back. Bottom: recover guard or stand up.",
    constraints: "Top cannot choke. Bottom must keep head and shoulders covered.",
    cues: "If you can see their shoulders, you can take their back. If you only see their head, nothing.",
    realWorld: "Turtle is a common survival position. Knowing how to attack and escape it is essential.",
    easier: "Top can use a body lock.",
    harder: "Striking threat for the top player.",
  },
];

// Helpers
export function getByPhase(phase) {
  return games.filter(g => g.phase === phase);
}

export function getRandom() {
  return games[Math.floor(Math.random() * games.length)];
}

export function getByPosition(position) {
  return games.filter(g => g.position.toLowerCase().includes(position.toLowerCase()));
}

export function search(term) {
  const t = term.toLowerCase();
  return games.filter(g =>
    g.name.toLowerCase().includes(t) ||
    g.skill.toLowerCase().includes(t) ||
    g.position.toLowerCase().includes(t)
  );
}

export const phaseNames = {
  0: "Cross-Phase",
  1: "Phase 1: Threshold & Connection",
  2: "Phase 2: Force Dissipation",
  3: "Phase 3: Adaptive Architecture",
  4: "Phase 4: The Inner Crucible",
};

export const positions = [...new Set(games.map(g => g.position))];

export default games;
